### ISSUE TITLE
Allow for multiple speakers

### ISSUE THREAD

**Issue by marc-bouvier** [watch-devtube/web#50]
Sometimes there are several people talking during a keynote. 

In the following example Rebecca Parsons is not visible until you read the description of the video.
https://dev.tube/video/-4fA_UciDaA

**Comment by sizovs** [comment]
@marc-bouvier Finally we added support for multiple speakers. 

```
speaker:
    - name: Martin Fowler
      twitter: martinfowler
    - name: Rebecca Parsons
      twitter: rebeccaparsons
```

![image](https://user-images.githubusercontent.com/2264968/79051650-78df7500-7c5b-11ea-965c-a1fe7c201ed7.png)
